---
title: "Applied Stats Project 0"
author: "Jami Watson"
date: "2025-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
df<-read.csv("https://raw.githubusercontent.com/nurfnick/Data_Sets_For_Stats/refs/heads/master/CuratedDataSets/24GAChittingstatsUpdate.csv", fileEncoding = "UTF-8")

head(df)
```

```{r}
View(df)
```

```{r}
summary(df$RBI)
```
```{r}
sd(df$RBI, na.rm = TRUE)
```
```{r}
hist(df$RBI, 
     main = "Histogram of RBI", 
     xlab = "RBI", 
     ylab = "Frequency", 
     col = "blue", 
     border = "black")
```
```{r}
boxplot(df$RBI, 
        main = "Box Plot of RBI", 
        ylab = "Values", 
        col = "lightblue", 
        border = "black", 
        horizontal = FALSE)
```
```{r}
qqnorm(df$RBI, main = "QQ Plot of RBI")
qqline(df$RBI, col = "red", lwd = 2)  # Adds a reference line
```

```{r}
freq_table <- table(df$Team)
print(freq_table)
```
```{r}
rel_freq_table <- prop.table(freq_table)
print(rel_freq_table)
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
